apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: keycloak
spec:
  tls:
    - hosts:
      - keycloak.home.com
  rules:
  - host: keycloak.home.com
    http:
      paths:
      - backend:
          serviceName: keycloak
          servicePort: 8080

